// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnrrobcabcusabidttrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhucnJvYmNhYmN1c2FiaWR0dHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTQ4NzksImV4cCI6MjA2ODgzMDg3OX0.QTksFZCFyupoP6JZwcL1mI8T6XRzHH3WvGRcrNZqzq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});